version: "3.9"
services:
  postgres:
    image: postgres:16.4
    container_name: myfood_db
    environment:
      POSTGRES_DB: myfood_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0102
    ports:
      - "5434:5432"
#    volumes:
#      - pgdbdata:/var/lib/postgresql/data
#
#  java:
#    build: .
#    ports:
#      - "8081:8081"
#    depends_on:
#      postgres:
#        condition: service_started
#    environment:
#      - DB_HOST=db_postgres
#
#
#volumes:
#  pgdbdata: null